//
//  DevelopmentSnapshot.swift
//  Maria's Notebook
//
//  Model for storing student development analysis results generated by MCP
//

import Foundation
import OSLog
import SwiftData

/// Stores a point-in-time analysis of a student's development and progress
@Model
final class DevelopmentSnapshot: Identifiable {

    private static let logger = Logger.database

    // MARK: - Identity & Metadata
    
    var id: UUID = UUID()
    
    /// The student this snapshot belongs to (CloudKit compatible string)
    var studentID: String = ""
    
    /// When this analysis was generated
    var generatedAt: Date = Date()
    
    /// Number of days of data analyzed
    var lookbackDays: Int = 30
    
    /// Version of the analysis algorithm used
    var analysisVersion: String = "1.0"
    
    // MARK: - Summary
    
    /// High-level summary of the student's overall progress
    var overallProgress: String = ""
    
    /// Key areas where the student is excelling (stored as JSON array)
    @Attribute(.externalStorage)
    private var keyStrengthsData: Data?
    
    /// Areas identified for continued growth (stored as JSON array)
    @Attribute(.externalStorage)
    private var areasForGrowthData: Data?
    
    /// Developmental milestones observed or achieved (stored as JSON array)
    @Attribute(.externalStorage)
    private var developmentalMilestonesData: Data?
    
    // MARK: - Insights
    
    /// Observed behavioral and learning patterns (stored as JSON array)
    @Attribute(.externalStorage)
    private var observedPatternsData: Data?
    
    /// Trends in behavior over the analysis period (stored as JSON array)
    @Attribute(.externalStorage)
    private var behavioralTrendsData: Data?
    
    /// Social and emotional development insights (stored as JSON array)
    @Attribute(.externalStorage)
    private var socialEmotionalInsightsData: Data?
    
    // MARK: - Recommendations
    
    /// Suggested next lessons based on observed readiness (stored as JSON array)
    @Attribute(.externalStorage)
    private var recommendedNextLessonsData: Data?
    
    /// Specific areas to focus practice efforts (stored as JSON array)
    @Attribute(.externalStorage)
    private var suggestedPracticeFocusData: Data?
    
    /// Intervention suggestions if challenges are identified (stored as JSON array)
    @Attribute(.externalStorage)
    private var interventionSuggestionsData: Data?
    
    // MARK: - Metrics
    
    /// Number of notes analyzed for this snapshot
    var totalNotesAnalyzed: Int = 0
    
    /// Number of practice sessions analyzed
    var practiceSessionsAnalyzed: Int = 0
    
    /// Number of work completions analyzed
    var workCompletionsAnalyzed: Int = 0
    
    /// Average practice quality score (1-5 scale)
    var averagePracticeQuality: Double?
    
    /// Average independence level (1-5 scale)
    var independenceLevel: Double?
    
    // MARK: - Raw Data
    
    /// Raw JSON response from MCP analysis (for debugging and audit)
    @Attribute(.externalStorage)
    var rawAnalysisJSON: String = ""
    
    /// User-added notes or comments about this snapshot
    var userNotes: String = ""
    
    /// Whether this snapshot has been reviewed by the teacher
    var isReviewed: Bool = false
    
    /// Whether this snapshot has been shared with parents
    var sharedWithParents: Bool = false
    
    /// Date when shared with parents (if applicable)
    var sharedAt: Date?
    
    // MARK: - Computed Properties for Arrays
    
    var keyStrengths: [String] {
        get { decodeStringArray(from: keyStrengthsData) }
        set { keyStrengthsData = encodeStringArray(newValue) }
    }
    
    var areasForGrowth: [String] {
        get { decodeStringArray(from: areasForGrowthData) }
        set { areasForGrowthData = encodeStringArray(newValue) }
    }
    
    var developmentalMilestones: [String] {
        get { decodeStringArray(from: developmentalMilestonesData) }
        set { developmentalMilestonesData = encodeStringArray(newValue) }
    }
    
    var observedPatterns: [String] {
        get { decodeStringArray(from: observedPatternsData) }
        set { observedPatternsData = encodeStringArray(newValue) }
    }
    
    var behavioralTrends: [String] {
        get { decodeStringArray(from: behavioralTrendsData) }
        set { behavioralTrendsData = encodeStringArray(newValue) }
    }
    
    var socialEmotionalInsights: [String] {
        get { decodeStringArray(from: socialEmotionalInsightsData) }
        set { socialEmotionalInsightsData = encodeStringArray(newValue) }
    }
    
    var recommendedNextLessons: [String] {
        get { decodeStringArray(from: recommendedNextLessonsData) }
        set { recommendedNextLessonsData = encodeStringArray(newValue) }
    }
    
    var suggestedPracticeFocus: [String] {
        get { decodeStringArray(from: suggestedPracticeFocusData) }
        set { suggestedPracticeFocusData = encodeStringArray(newValue) }
    }
    
    var interventionSuggestions: [String] {
        get { decodeStringArray(from: interventionSuggestionsData) }
        set { interventionSuggestionsData = encodeStringArray(newValue) }
    }
    
    // MARK: - Initialization
    
    init(
        id: UUID = UUID(),
        studentID: String,
        generatedAt: Date = Date(),
        lookbackDays: Int = 30,
        analysisVersion: String = "1.0",
        overallProgress: String = "",
        keyStrengths: [String] = [],
        areasForGrowth: [String] = [],
        developmentalMilestones: [String] = [],
        observedPatterns: [String] = [],
        behavioralTrends: [String] = [],
        socialEmotionalInsights: [String] = [],
        recommendedNextLessons: [String] = [],
        suggestedPracticeFocus: [String] = [],
        interventionSuggestions: [String] = [],
        totalNotesAnalyzed: Int = 0,
        practiceSessionsAnalyzed: Int = 0,
        workCompletionsAnalyzed: Int = 0,
        averagePracticeQuality: Double? = nil,
        independenceLevel: Double? = nil,
        rawAnalysisJSON: String = ""
    ) {
        self.id = id
        self.studentID = studentID
        self.generatedAt = generatedAt
        self.lookbackDays = lookbackDays
        self.analysisVersion = analysisVersion
        self.overallProgress = overallProgress
        self.keyStrengthsData = Self.encodeStringArray(keyStrengths)
        self.areasForGrowthData = Self.encodeStringArray(areasForGrowth)
        self.developmentalMilestonesData = Self.encodeStringArray(developmentalMilestones)
        self.observedPatternsData = Self.encodeStringArray(observedPatterns)
        self.behavioralTrendsData = Self.encodeStringArray(behavioralTrends)
        self.socialEmotionalInsightsData = Self.encodeStringArray(socialEmotionalInsights)
        self.recommendedNextLessonsData = Self.encodeStringArray(recommendedNextLessons)
        self.suggestedPracticeFocusData = Self.encodeStringArray(suggestedPracticeFocus)
        self.interventionSuggestionsData = Self.encodeStringArray(interventionSuggestions)
        self.totalNotesAnalyzed = totalNotesAnalyzed
        self.practiceSessionsAnalyzed = practiceSessionsAnalyzed
        self.workCompletionsAnalyzed = workCompletionsAnalyzed
        self.averagePracticeQuality = averagePracticeQuality
        self.independenceLevel = independenceLevel
        self.rawAnalysisJSON = rawAnalysisJSON
    }
    
    // MARK: - Helper Methods
    
    /// Returns the student UUID from the stored string
    var studentUUID: UUID? {
        UUID(uuidString: studentID)
    }
    
    /// Returns true if this snapshot has actionable intervention suggestions
    var hasInterventions: Bool {
        !interventionSuggestions.isEmpty
    }
    
    /// Returns true if this snapshot contains sufficient data for meaningful analysis
    var hasSufficientData: Bool {
        totalNotesAnalyzed >= 3 || practiceSessionsAnalyzed >= 2
    }
    
    /// Returns a formatted summary for display
    var displaySummary: String {
        """
        Generated: \(generatedAt.formatted(date: .abbreviated, time: .omitted))
        Period: \(lookbackDays) days
        Data: \(totalNotesAnalyzed) notes, \(practiceSessionsAnalyzed) sessions, \(workCompletionsAnalyzed) completions
        """
    }
    
    // MARK: - Private Encoding/Decoding
    
    private func decodeStringArray(from data: Data?) -> [String] {
        guard let data else { return [] }
        do {
            return try JSONDecoder().decode([String].self, from: data)
        } catch {
            Self.logger.warning("Failed to decode string array: \(error.localizedDescription)")
            return []
        }
    }

    private func encodeStringArray(_ array: [String]) -> Data? {
        Self.encodeStringArray(array)
    }

    private static func encodeStringArray(_ array: [String]) -> Data? {
        do {
            return try JSONEncoder().encode(array)
        } catch {
            Self.logger.warning("Failed to encode string array: \(error.localizedDescription)")
            return nil
        }
    }
}
