import SwiftUI
import SwiftData

/// A consolidated, print-friendly view of open work items.
/// Designed to conserve paper while maintaining readability.
struct WorkPrintView: View {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String

    @Environment(\.modelContext) private var modelContext

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            printHeader

            Divider()
                .padding(.vertical, 8)

            // Work items grouped by student
            ForEach(Array(groupedWork.enumerated()), id: \.offset) { index, group in
                studentSection(title: group.title, works: group.works)

                if index < groupedWork.count - 1 {
                    Divider()
                        .padding(.vertical, 12)
                }
            }

            Spacer()

            // Footer
            printFooter
        }
        .padding(20)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        .background(Color.white)
    }

    private var printHeader: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text("Open Work Report")
                    .font(AppTheme.ScaledFont.titleSmall)
                Spacer()
                Text(Date().formatted(date: .abbreviated, time: .omitted))
                    .font(AppTheme.ScaledFont.captionSmall)
                    .foregroundStyle(.secondary)
            }

            if !filterDescription.isEmpty {
                Text("Filter: \(filterDescription)")
                    .font(AppTheme.ScaledFont.captionSmall)
                    .foregroundStyle(.secondary)
            }

            if !sortDescription.isEmpty {
                Text("Sort: \(sortDescription)")
                    .font(AppTheme.ScaledFont.captionSmall)
                    .foregroundStyle(.secondary)
            }

            Text(
                "\(workItems.count) work item\(workItems.count == 1 ? "" : "s")" +
                " \u{2022} \(groupedWork.count) student\(groupedWork.count == 1 ? "" : "s")"
            )
                .font(AppTheme.ScaledFont.captionSmall)
                .foregroundStyle(.secondary)
        }
    }

    private var printFooter: some View {
        HStack {
            Text("Generated by Maria's Notebook")
                .font(AppTheme.ScaledFont.captionSmall)
                .foregroundStyle(.secondary)
            Spacer()
        }
    }

    @ViewBuilder
    private func studentSection(title: String, works: [WorkModel]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            // Student name header
            Text(title)
                .font(AppTheme.ScaledFont.bodySemibold)
                .padding(.bottom, 4)

            // Work items for this student
            ForEach(Array(works.enumerated()), id: \.offset) { index, work in
                workItemRow(work: work, index: index + 1)
            }
        }
    }

    @ViewBuilder
    private func workItemRow(work: WorkModel, index: Int) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .top, spacing: 8) {
                // Index number
                Text("\(index).")
                    .font(AppTheme.ScaledFont.captionSmallSemibold)
                    .foregroundStyle(.secondary)
                    .frame(width: 20, alignment: .trailing)

                VStack(alignment: .leading, spacing: 3) {
                    // Lesson name
                    if let lessonID = UUID(uuidString: work.lessonID),
                       let lesson = lessons.first(where: { $0.id == lessonID }) {
                        HStack(spacing: 6) {
                            Circle()
                                .fill(AppColors.color(forSubject: lesson.subject))
                                .frame(width: 6, height: 6)

                            Text(lesson.name)
                                .font(AppTheme.ScaledFont.captionSemibold)
                        }
                    } else {
                        Text("Lesson")
                            .font(AppTheme.ScaledFont.captionSemibold)
                            .foregroundStyle(.secondary)
                    }

                    // Work kind and status
                    HStack(spacing: 8) {
                        if let kind = work.kind {
                            Text(kind.displayName)
                                .font(AppTheme.ScaledFont.captionSmall)
                                .foregroundStyle(.secondary)
                        }

                        if work.status != .active {
                            Text("\u{2022}")
                                .font(AppTheme.ScaledFont.captionSmall)
                                .foregroundStyle(.secondary)

                            Text(work.status.displayName)
                                .font(AppTheme.ScaledFont.captionSmall)
                                .foregroundStyle(.secondary)
                        }

                        // Due date
                        if let dueAt = work.dueAt {
                            Text("\u{2022}")
                                .font(AppTheme.ScaledFont.captionSmall)
                                .foregroundStyle(.secondary)

                            Text("Due: \(dueAt.formatted(date: .abbreviated, time: .omitted))")
                                .font(AppTheme.ScaledFont.captionSmall)
                                .foregroundStyle(dueAt < Date() ? .red : .secondary)
                        }
                    }

                    // Title (if present)
                    if !work.title.isEmpty {
                        Text(work.title)
                            .font(AppTheme.ScaledFont.captionSmall)
                            .foregroundStyle(.primary)
                    }

                    // Notes (if present and brief)
                    if !work.latestUnifiedNoteText.isEmpty {
                        Text(work.latestUnifiedNoteText)
                            .font(AppTheme.ScaledFont.captionSmall)
                            .foregroundStyle(.secondary)
                            .lineLimit(2)
                            .padding(.top, 1)
                    }

                    // Steps summary (for reports)
                    if work.isReport {
                        let progress = work.stepProgress
                        if progress.total > 0 {
                            HStack(spacing: 4) {
                                Image(systemName: "checklist")
                                    .font(.system(size: 9))
                                Text("\(progress.completed)/\(progress.total) steps completed")
                                    .font(AppTheme.ScaledFont.captionSmall)
                            }
                            .foregroundStyle(.secondary)
                            .padding(.top, 1)
                        }
                    }
                }

                Spacer()

                // Checkbox for tracking
                Image(systemName: "square")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 6)
        .padding(.horizontal, 8)
        .background(
            RoundedRectangle(cornerRadius: 6)
                .fill(Color.black.opacity(0.02))
        )
    }
}

// MARK: - Extensions
// Note: WorkKind and WorkStatus displayName properties are defined in WorkTypes.swift
