import SwiftUI
import SwiftData

/// A consolidated, print-friendly view of open work items.
/// Designed to conserve paper while maintaining readability.
struct WorkPrintView: View {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    @Environment(\.modelContext) private var modelContext
    
    private struct WorkPrintGroup: Identifiable {
        let id: String
        let title: String
        let student: Student?
        let works: [WorkModel]
    }

    private var groupedWork: [WorkPrintGroup] {
        // Group work by student for clearer organization
        let studentDict = Dictionary(grouping: workItems) { work in
            work.studentID
        }

        let groups: [WorkPrintGroup] = studentDict.map { (studentIDString, works) in
            let studentID = UUID(uuidString: studentIDString)
            let student = studentID.flatMap { id in students.first(where: { $0.id == id }) }
            let title: String
            if let student = student {
                title = student.fullName
            } else if studentIDString.trimmed().isEmpty {
                title = "Unassigned Student"
            } else {
                title = "Unknown Student"
            }

            let sorted = works.sorted { work1, work2 in
                // Sort by due date, then by assigned date
                if let due1 = work1.dueAt, let due2 = work2.dueAt {
                    return due1 < due2
                }
                if work1.dueAt != nil { return true }
                if work2.dueAt != nil { return false }
                return work1.assignedAt < work2.assignedAt
            }

            let groupID = studentIDString.trimmed().isEmpty ? "unassigned" : studentIDString
            return WorkPrintGroup(id: groupID, title: title, student: student, works: sorted)
        }

        return groups.sorted { lhs, rhs in
            if lhs.student != nil && rhs.student == nil { return true }
            if lhs.student == nil && rhs.student != nil { return false }
            return lhs.title < rhs.title
        }
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            printHeader
            
            Divider()
                .padding(.vertical, 8)
            
            // Work items grouped by student
            ForEach(Array(groupedWork.enumerated()), id: \.offset) { index, group in
                studentSection(title: group.title, works: group.works)
                
                if index < groupedWork.count - 1 {
                    Divider()
                        .padding(.vertical, 12)
                }
            }
            
            Spacer()
            
            // Footer
            printFooter
        }
        .padding(20)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        .background(Color.white)
    }
    
    private var printHeader: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text("Open Work Report")
                    .font(.system(size: 18, weight: .bold))
                Spacer()
                Text(Date().formatted(date: .abbreviated, time: .omitted))
                    .font(.system(size: 11))
                    .foregroundStyle(.secondary)
            }
            
            if !filterDescription.isEmpty {
                Text("Filter: \(filterDescription)")
                    .font(.system(size: 10))
                    .foregroundStyle(.secondary)
            }
            
            if !sortDescription.isEmpty {
                Text("Sort: \(sortDescription)")
                    .font(.system(size: 10))
                    .foregroundStyle(.secondary)
            }
            
            Text("\(workItems.count) work item\(workItems.count == 1 ? "" : "s") • \(groupedWork.count) student\(groupedWork.count == 1 ? "" : "s")")
                .font(.system(size: 10))
                .foregroundStyle(.secondary)
        }
    }
    
    private var printFooter: some View {
        HStack {
            Text("Generated by Maria's Notebook")
                .font(.system(size: 9))
                .foregroundStyle(.secondary)
            Spacer()
        }
    }
    
    @ViewBuilder
    private func studentSection(title: String, works: [WorkModel]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            // Student name header
            Text(title)
                .font(.system(size: 14, weight: .semibold))
                .padding(.bottom, 4)
            
            // Work items for this student
            ForEach(Array(works.enumerated()), id: \.offset) { index, work in
                workItemRow(work: work, index: index + 1)
            }
        }
    }
    
    @ViewBuilder
    private func workItemRow(work: WorkModel, index: Int) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .top, spacing: 8) {
                // Index number
                Text("\(index).")
                    .font(.system(size: 11, weight: .medium, design: .rounded))
                    .foregroundStyle(.secondary)
                    .frame(width: 20, alignment: .trailing)
                
                VStack(alignment: .leading, spacing: 3) {
                    // Lesson name
                    if let lessonID = UUID(uuidString: work.lessonID),
                       let lesson = lessons.first(where: { $0.id == lessonID }) {
                        HStack(spacing: 6) {
                            Circle()
                                .fill(AppColors.color(forSubject: lesson.subject))
                                .frame(width: 6, height: 6)
                            
                            Text(lesson.name)
                                .font(.system(size: 12, weight: .medium))
                        }
                    } else {
                        Text("Lesson")
                            .font(.system(size: 12, weight: .medium))
                            .foregroundStyle(.secondary)
                    }
                    
                    // Work kind and status
                    HStack(spacing: 8) {
                        if let kind = work.kind {
                            Text(kind.displayName)
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                        }
                        
                        if work.status != .active {
                            Text("•")
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                            
                            Text(work.status.displayName)
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                        }
                        
                        // Due date
                        if let dueAt = work.dueAt {
                            Text("•")
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                            
                            Text("Due: \(dueAt.formatted(date: .abbreviated, time: .omitted))")
                                .font(.system(size: 10))
                                .foregroundStyle(dueAt < Date() ? .red : .secondary)
                        }
                    }
                    
                    // Title (if present)
                    if !work.title.isEmpty {
                        Text(work.title)
                            .font(.system(size: 11))
                            .foregroundStyle(.primary)
                    }
                    
                    // Notes (if present and brief)
                    if !work.notes.isEmpty {
                        Text(work.notes)
                            .font(.system(size: 10))
                            .foregroundStyle(.secondary)
                            .lineLimit(2)
                            .padding(.top, 1)
                    }
                    
                    // Steps summary (for reports)
                    if work.isReport {
                        let progress = work.stepProgress
                        if progress.total > 0 {
                            HStack(spacing: 4) {
                                Image(systemName: "checklist")
                                    .font(.system(size: 9))
                                Text("\(progress.completed)/\(progress.total) steps completed")
                                    .font(.system(size: 10))
                            }
                            .foregroundStyle(.secondary)
                            .padding(.top, 1)
                        }
                    }
                }
                
                Spacer()
                
                // Checkbox for tracking
                Image(systemName: "square")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 6)
        .padding(.horizontal, 8)
        .background(
            RoundedRectangle(cornerRadius: 6)
                .fill(Color.black.opacity(0.02))
        )
    }
}

#if os(iOS)
import UIKit

/// Helper to render SwiftUI views to PDF on iOS
@MainActor
struct PDFRenderer {
    static func render<Content: View>(view: Content, size: CGSize) -> Data? {
        let hostingController = UIHostingController(rootView: view.frame(width: size.width, height: size.height))
        hostingController.view.bounds = CGRect(origin: .zero, size: size)
        hostingController.view.backgroundColor = .white

        // CRITICAL: The hosting controller's view must be in the view hierarchy for SwiftUI to render.
        // Add it to a temporary window positioned offscreen.
        let tempWindow = UIWindow(frame: CGRect(x: TimeoutConstants.offscreenCoordinate, y: TimeoutConstants.offscreenCoordinate, width: size.width, height: size.height))
        tempWindow.rootViewController = hostingController
        tempWindow.isHidden = false
        tempWindow.layoutIfNeeded()

        // Force layout and give SwiftUI time to render
        hostingController.view.setNeedsLayout()
        hostingController.view.layoutIfNeeded()

        // Allow the run loop to process pending layout
        RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.1))

        let pdfRenderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: size))
        let data = pdfRenderer.pdfData { context in
            context.beginPage()
            hostingController.view.layer.render(in: context.cgContext)
        }

        // Clean up: remove from window hierarchy
        tempWindow.isHidden = true
        tempWindow.rootViewController = nil

        return data
    }
}
#endif

#if os(macOS)
import AppKit
import PDFKit

/// macOS-specific print controller
struct WorkPrintController: NSViewRepresentable {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String

    func makeNSView(context: Context) -> NSView {
        let view = NSView()

        DispatchQueue.main.async {
            self.printContent()
        }

        return view
    }

    func updateNSView(_ nsView: NSView, context: Context) {}

    private func printContent() {
        let printableWidth: CGFloat = 612 - 72 // Page width minus margins

        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )

        guard let pdfData = renderViewToPDF(printView, width: printableWidth) else { return }

        guard let printInfo = NSPrintInfo.shared.copy() as? NSPrintInfo else { return }
        printInfo.topMargin = 36
        printInfo.bottomMargin = 36
        printInfo.leftMargin = 36
        printInfo.rightMargin = 36
        printInfo.jobDisposition = .preview

        if let doc = PDFDocument(data: pdfData),
           let operation = doc.printOperation(for: printInfo, scalingMode: .pageScaleToFit, autoRotate: false) {
            operation.showsPrintPanel = true
            operation.showsProgressPanel = true
            operation.run()
        }
    }

    private func renderViewToPDF<V: View>(_ view: V, width: CGFloat) -> Data? {
        let hostingView = NSHostingView(rootView: view)
        hostingView.appearance = NSAppearance(named: .aqua)

        let tempWindow = NSWindow(
            contentRect: NSRect(x: TimeoutConstants.offscreenCoordinate, y: TimeoutConstants.offscreenCoordinate, width: width, height: 2000),
            styleMask: [.titled],
            backing: .buffered,
            defer: false
        )
        tempWindow.contentView = hostingView
        tempWindow.backgroundColor = .white
        tempWindow.makeKeyAndOrderFront(nil)

        hostingView.frame = NSRect(x: 0, y: 0, width: width, height: 2000)
        hostingView.needsLayout = true
        hostingView.layoutSubtreeIfNeeded()

        RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.2))

        let fittingSize = hostingView.fittingSize
        let finalHeight = max(fittingSize.height, 100)
        let finalSize = NSSize(width: width, height: finalHeight)

        hostingView.setFrameSize(finalSize)
        tempWindow.setContentSize(finalSize)
        hostingView.needsLayout = true
        hostingView.layoutSubtreeIfNeeded()

        RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.2))

        let image = NSImage(size: finalSize)
        image.lockFocus()
        NSColor.white.setFill()
        NSRect(origin: .zero, size: finalSize).fill()
        if let context = NSGraphicsContext.current?.cgContext {
            hostingView.layer?.render(in: context)
        }
        image.unlockFocus()

        guard let tiffData = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData),
              let cgImage = bitmap.cgImage else {
            tempWindow.orderOut(nil)
            return nil
        }

        let pdfData = NSMutableData()
        var mediaBox = CGRect(origin: .zero, size: finalSize)

        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData),
              let pdfContext = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            tempWindow.orderOut(nil)
            return nil
        }

        pdfContext.beginPDFPage(nil)
        pdfContext.draw(cgImage, in: mediaBox)
        pdfContext.endPDFPage()
        pdfContext.closePDF()

        tempWindow.orderOut(nil)
        return pdfData as Data
    }
}
#endif

/// Sheet wrapper for presenting the print interface
struct WorkPrintSheet: View {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        #if os(iOS)
        VStack(spacing: 0) {
            // Preview the print view
            ScrollView {
                WorkPrintView(
                    workItems: workItems,
                    students: students,
                    lessons: lessons,
                    filterDescription: filterDescription,
                    sortDescription: sortDescription
                )
                .frame(width: 612 * 0.5, height: 792 * 0.5) // 50% scale for preview
                .scaleEffect(0.5)
                .frame(width: 612 * 0.5, height: 792 * 0.5)
            }
            .background(Color.gray.opacity(0.1))
            
            Divider()
            
            HStack {
                Button("Cancel") {
                    dismiss()
                }
                
                Spacer()
                
                Button("Print", systemImage: "printer") {
                    presentPrint()
                }
                .keyboardShortcut(.defaultAction)
            }
            .padding()
        }
        #else
        VStack(spacing: 16) {
            HStack {
                Text("Print Preview")
                    .font(.headline)
                Spacer()
                Button("Close") {
                    dismiss()
                }
            }
            
            ScrollView {
                WorkPrintView(
                    workItems: workItems,
                    students: students,
                    lessons: lessons,
                    filterDescription: filterDescription,
                    sortDescription: sortDescription
                )
                .frame(width: 612 * 0.6, height: 792 * 0.6)
                .scaleEffect(0.6)
                .frame(width: 612 * 0.6, height: 792 * 0.6)
            }
            .background(Color.gray.opacity(0.1))
            
            HStack {
                Button("Cancel") {
                    dismiss()
                }
                
                Spacer()
                
                Button("Print", systemImage: "printer") {
                    presentPrint()
                }
                .keyboardShortcut(.defaultAction)
            }
        }
        .padding()
        .frame(minWidth: 500, minHeight: 700)
        #endif
    }
    
    private func presentPrint() {
        #if os(iOS)
        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )
        
        if let pdfData = PDFRenderer.render(view: printView, size: CGSize(width: 612, height: 792)) {
            let printController = UIPrintInteractionController.shared
            printController.printingItem = pdfData
            
            let printInfo = UIPrintInfo.printInfo()
            printInfo.outputType = .general
            printInfo.jobName = "Open Work Report"
            printController.printInfo = printInfo
            
            printController.present(animated: true) { _, completed, error in
                if completed {
                    dismiss()
                }
            }
        }
        #else
        let printableWidth: CGFloat = 612 - 72

        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )

        guard let pdfData = renderSheetViewToPDF(printView, width: printableWidth) else {
            dismiss()
            return
        }

        guard let printInfo = NSPrintInfo.shared.copy() as? NSPrintInfo else { return }
        printInfo.topMargin = 36
        printInfo.bottomMargin = 36
        printInfo.leftMargin = 36
        printInfo.rightMargin = 36

        if let doc = PDFDocument(data: pdfData),
           let keyWindow = NSApp.keyWindow,
           let operation = doc.printOperation(for: printInfo, scalingMode: .pageScaleToFit, autoRotate: false) {
            operation.showsPrintPanel = true
            operation.runModal(for: keyWindow, delegate: nil, didRun: nil, contextInfo: nil)
        }
        dismiss()
        #endif
    }

    #if os(macOS)
    private func renderSheetViewToPDF<V: View>(_ view: V, width: CGFloat) -> Data? {
        let hostingView = NSHostingView(rootView: view)
        hostingView.appearance = NSAppearance(named: .aqua)

        let tempWindow = NSWindow(
            contentRect: NSRect(x: TimeoutConstants.offscreenCoordinate, y: TimeoutConstants.offscreenCoordinate, width: width, height: 2000),
            styleMask: [.titled],
            backing: .buffered,
            defer: false
        )
        tempWindow.contentView = hostingView
        tempWindow.backgroundColor = .white
        tempWindow.makeKeyAndOrderFront(nil)

        hostingView.frame = NSRect(x: 0, y: 0, width: width, height: 2000)
        hostingView.needsLayout = true
        hostingView.layoutSubtreeIfNeeded()

        RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.2))

        let fittingSize = hostingView.fittingSize
        let finalHeight = max(fittingSize.height, 100)
        let finalSize = NSSize(width: width, height: finalHeight)

        hostingView.setFrameSize(finalSize)
        tempWindow.setContentSize(finalSize)
        hostingView.needsLayout = true
        hostingView.layoutSubtreeIfNeeded()

        RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.2))

        let image = NSImage(size: finalSize)
        image.lockFocus()
        NSColor.white.setFill()
        NSRect(origin: .zero, size: finalSize).fill()
        if let context = NSGraphicsContext.current?.cgContext {
            hostingView.layer?.render(in: context)
        }
        image.unlockFocus()

        guard let tiffData = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData),
              let cgImage = bitmap.cgImage else {
            tempWindow.orderOut(nil)
            return nil
        }

        let pdfData = NSMutableData()
        var mediaBox = CGRect(origin: .zero, size: finalSize)

        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData),
              let pdfContext = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            tempWindow.orderOut(nil)
            return nil
        }

        pdfContext.beginPDFPage(nil)
        pdfContext.draw(cgImage, in: mediaBox)
        pdfContext.endPDFPage()
        pdfContext.closePDF()

        tempWindow.orderOut(nil)
        return pdfData as Data
    }
    #endif
}

// MARK: - Extensions
// Note: WorkKind and WorkStatus displayName properties are defined in WorkTypes.swift
