import SwiftUI
import SwiftData

/// A consolidated, print-friendly view of open work items.
/// Designed to conserve paper while maintaining readability.
struct WorkPrintView: View {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    @Environment(\.modelContext) private var modelContext
    
    private var groupedWork: [(Student, [WorkModel])] {
        // Group work by student for clearer organization
        let studentDict = Dictionary(grouping: workItems) { work in
            work.studentID
        }
        
        return studentDict.compactMap { (studentIDString, works) in
            guard let studentID = UUID(uuidString: studentIDString),
                  let student = students.first(where: { $0.id == studentID }) else {
                return nil
            }
            let sorted = works.sorted { work1, work2 in
                // Sort by due date, then by assigned date
                if let due1 = work1.dueAt, let due2 = work2.dueAt {
                    return due1 < due2
                }
                if work1.dueAt != nil { return true }
                if work2.dueAt != nil { return false }
                return work1.assignedAt < work2.assignedAt
            }
            return (student, sorted)
        }.sorted { $0.0.fullName < $1.0.fullName }
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            printHeader
            
            Divider()
                .padding(.vertical, 8)
            
            // Work items grouped by student
            ForEach(Array(groupedWork.enumerated()), id: \.offset) { index, group in
                studentSection(student: group.0, works: group.1)
                
                if index < groupedWork.count - 1 {
                    Divider()
                        .padding(.vertical, 12)
                }
            }
            
            Spacer()
            
            // Footer
            printFooter
        }
        .padding(20)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        .background(Color.white)
    }
    
    private var printHeader: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text("Open Work Report")
                    .font(.system(size: 18, weight: .bold))
                Spacer()
                Text(Date().formatted(date: .abbreviated, time: .omitted))
                    .font(.system(size: 11))
                    .foregroundStyle(.secondary)
            }
            
            if !filterDescription.isEmpty {
                Text("Filter: \(filterDescription)")
                    .font(.system(size: 10))
                    .foregroundStyle(.secondary)
            }
            
            if !sortDescription.isEmpty {
                Text("Sort: \(sortDescription)")
                    .font(.system(size: 10))
                    .foregroundStyle(.secondary)
            }
            
            Text("\(workItems.count) work item\(workItems.count == 1 ? "" : "s") • \(groupedWork.count) student\(groupedWork.count == 1 ? "" : "s")")
                .font(.system(size: 10))
                .foregroundStyle(.secondary)
        }
    }
    
    private var printFooter: some View {
        HStack {
            Text("Generated by Maria's Notebook")
                .font(.system(size: 9))
                .foregroundStyle(.secondary)
            Spacer()
        }
    }
    
    @ViewBuilder
    private func studentSection(student: Student, works: [WorkModel]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            // Student name header
            Text(student.fullName)
                .font(.system(size: 14, weight: .semibold))
                .padding(.bottom, 4)
            
            // Work items for this student
            ForEach(Array(works.enumerated()), id: \.offset) { index, work in
                workItemRow(work: work, index: index + 1)
            }
        }
    }
    
    @ViewBuilder
    private func workItemRow(work: WorkModel, index: Int) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .top, spacing: 8) {
                // Index number
                Text("\(index).")
                    .font(.system(size: 11, weight: .medium, design: .rounded))
                    .foregroundStyle(.secondary)
                    .frame(width: 20, alignment: .trailing)
                
                VStack(alignment: .leading, spacing: 3) {
                    // Lesson name
                    if let lessonID = UUID(uuidString: work.lessonID),
                       let lesson = lessons.first(where: { $0.id == lessonID }) {
                        HStack(spacing: 6) {
                            Circle()
                                .fill(AppColors.color(forSubject: lesson.subject))
                                .frame(width: 6, height: 6)
                            
                            Text(lesson.name)
                                .font(.system(size: 12, weight: .medium))
                        }
                    } else {
                        Text("Lesson")
                            .font(.system(size: 12, weight: .medium))
                            .foregroundStyle(.secondary)
                    }
                    
                    // Work kind and status
                    HStack(spacing: 8) {
                        if let kind = work.kind {
                            Text(kind.displayName)
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                        }
                        
                        if work.status != .active {
                            Text("•")
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                            
                            Text(work.status.displayName)
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                        }
                        
                        // Due date
                        if let dueAt = work.dueAt {
                            Text("•")
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                            
                            Text("Due: \(dueAt.formatted(date: .abbreviated, time: .omitted))")
                                .font(.system(size: 10))
                                .foregroundStyle(dueAt < Date() ? .red : .secondary)
                        }
                    }
                    
                    // Title (if present)
                    if !work.title.isEmpty {
                        Text(work.title)
                            .font(.system(size: 11))
                            .foregroundStyle(.primary)
                    }
                    
                    // Notes (if present and brief)
                    if !work.notes.isEmpty {
                        Text(work.notes)
                            .font(.system(size: 10))
                            .foregroundStyle(.secondary)
                            .lineLimit(2)
                            .padding(.top, 1)
                    }
                    
                    // Steps summary (for reports)
                    if work.isReport {
                        let progress = work.stepProgress
                        if progress.total > 0 {
                            HStack(spacing: 4) {
                                Image(systemName: "checklist")
                                    .font(.system(size: 9))
                                Text("\(progress.completed)/\(progress.total) steps completed")
                                    .font(.system(size: 10))
                            }
                            .foregroundStyle(.secondary)
                            .padding(.top, 1)
                        }
                    }
                }
                
                Spacer()
                
                // Checkbox for tracking
                Image(systemName: "square")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 6)
        .padding(.horizontal, 8)
        .background(
            RoundedRectangle(cornerRadius: 6)
                .fill(Color.black.opacity(0.02))
        )
    }
}

#if os(iOS)
/// iOS-specific print controller
struct WorkPrintController: UIViewControllerRepresentable {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    @Environment(\.dismiss) private var dismiss
    
    func makeUIViewController(context: Context) -> UIViewController {
        let controller = UIViewController()
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        // Create the print view
        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )
        
        // Render to PDF-ready format
        let renderer = ImageRenderer(content: printView.frame(width: 612, height: 792)) // US Letter
        
        if let pdfData = renderer.pdf() {
            let printController = UIPrintInteractionController.shared
            printController.printingItem = pdfData
            
            let printInfo = UIPrintInfo.printInfo()
            printInfo.outputType = .general
            printInfo.jobName = "Open Work Report"
            printController.printInfo = printInfo
            
            printController.present(animated: true) { _, completed, error in
                if completed {
                    print("Print job completed successfully")
                }
                if let error = error {
                    print("Print job failed: \(error.localizedDescription)")
                }
            }
        }
    }
}

extension ImageRenderer where Content == View {
    func pdf() -> Data? {
        let format = GraphicsImageRendererFormat()
        format.scale = 1.0
        
        let pdfRenderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: 612, height: 792))
        let data = pdfRenderer.pdfData { context in
            context.beginPage()
            
            // Render the view
            let controller = UIHostingController(rootView: self.content)
            controller.view.bounds = CGRect(x: 0, y: 0, width: 612, height: 792)
            controller.view.backgroundColor = .white
            
            let renderer = UIGraphicsImageRenderer(bounds: controller.view.bounds)
            let image = renderer.image { rendererContext in
                controller.view.layer.render(in: rendererContext.cgContext)
            }
            
            image.draw(in: CGRect(x: 0, y: 0, width: 612, height: 792))
        }
        
        return data
    }
}
#endif

#if os(macOS)
/// macOS-specific print controller
struct WorkPrintController: NSViewRepresentable {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    func makeNSView(context: Context) -> NSView {
        let view = NSView()
        
        DispatchQueue.main.async {
            self.printContent()
        }
        
        return view
    }
    
    func updateNSView(_ nsView: NSView, context: Context) {}
    
    private func printContent() {
        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )
        
        let hostingView = NSHostingView(rootView: printView.frame(width: 612, height: 792))
        hostingView.frame = CGRect(x: 0, y: 0, width: 612, height: 792)
        
        let printOperation = NSPrintOperation(view: hostingView)
        printOperation.printInfo.topMargin = 36
        printOperation.printInfo.bottomMargin = 36
        printOperation.printInfo.leftMargin = 36
        printOperation.printInfo.rightMargin = 36
        printOperation.printInfo.jobDisposition = .preview // Opens print preview
        
        printOperation.run()
    }
}
#endif

/// Sheet wrapper for presenting the print interface
struct WorkPrintSheet: View {
    let workItems: [WorkModel]
    let students: [Student]
    let lessons: [Lesson]
    let filterDescription: String
    let sortDescription: String
    
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        #if os(iOS)
        VStack(spacing: 0) {
            // Preview the print view
            ScrollView {
                WorkPrintView(
                    workItems: workItems,
                    students: students,
                    lessons: lessons,
                    filterDescription: filterDescription,
                    sortDescription: sortDescription
                )
                .frame(width: 612 * 0.5, height: 792 * 0.5) // 50% scale for preview
                .scaleEffect(0.5)
                .frame(width: 612 * 0.5, height: 792 * 0.5)
            }
            .background(Color.gray.opacity(0.1))
            
            Divider()
            
            HStack {
                Button("Cancel") {
                    dismiss()
                }
                
                Spacer()
                
                Button("Print", systemImage: "printer") {
                    presentPrint()
                }
                .keyboardShortcut(.defaultAction)
            }
            .padding()
        }
        #else
        VStack(spacing: 16) {
            HStack {
                Text("Print Preview")
                    .font(.headline)
                Spacer()
                Button("Close") {
                    dismiss()
                }
            }
            
            ScrollView {
                WorkPrintView(
                    workItems: workItems,
                    students: students,
                    lessons: lessons,
                    filterDescription: filterDescription,
                    sortDescription: sortDescription
                )
                .frame(width: 612 * 0.6, height: 792 * 0.6)
                .scaleEffect(0.6)
                .frame(width: 612 * 0.6, height: 792 * 0.6)
            }
            .background(Color.gray.opacity(0.1))
            
            HStack {
                Button("Cancel") {
                    dismiss()
                }
                
                Spacer()
                
                Button("Print", systemImage: "printer") {
                    presentPrint()
                }
                .keyboardShortcut(.defaultAction)
            }
        }
        .padding()
        .frame(minWidth: 500, minHeight: 700)
        #endif
    }
    
    private func presentPrint() {
        #if os(iOS)
        let renderer = ImageRenderer(content: WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        ).frame(width: 612, height: 792))
        
        if let pdfData = renderer.pdf() {
            let printController = UIPrintInteractionController.shared
            printController.printingItem = pdfData
            
            let printInfo = UIPrintInfo.printInfo()
            printInfo.outputType = .general
            printInfo.jobName = "Open Work Report"
            printController.printInfo = printInfo
            
            printController.present(animated: true) { _, completed, error in
                if completed {
                    dismiss()
                }
            }
        }
        #else
        let printView = WorkPrintView(
            workItems: workItems,
            students: students,
            lessons: lessons,
            filterDescription: filterDescription,
            sortDescription: sortDescription
        )
        
        let hostingView = NSHostingView(rootView: printView.frame(width: 612, height: 792))
        hostingView.frame = CGRect(x: 0, y: 0, width: 612, height: 792)
        
        let printOperation = NSPrintOperation(view: hostingView)
        printOperation.printInfo.topMargin = 36
        printOperation.printInfo.bottomMargin = 36
        printOperation.printInfo.leftMargin = 36
        printOperation.printInfo.rightMargin = 36
        
        printOperation.runModal(for: NSApp.keyWindow!, delegate: nil, didRun: nil, contextInfo: nil)
        dismiss()
        #endif
    }
}

// MARK: - Extensions

extension WorkKind {
    var displayName: String {
        switch self {
        case .practiceLesson: return "Practice"
        case .followUp: return "Follow Up"
        case .report: return "Report"
        case .research: return "Research"
        case .choice: return "Choice"
        }
    }
}

extension WorkStatus {
    var displayName: String {
        switch self {
        case .active: return "Active"
        case .review: return "Review"
        case .complete: return "Complete"
        }
    }
}
